spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/user_db
    username: user
    password: password
  kafka:
    bootstrap-servers: kafka:29092
  flyway:
    enabled: true
    url: jdbc:postgresql://postgres:5432/user_db
    user: user
    password: password
    schemas: public
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:/db/migration
    clean-disabled: true
    out-of-order: false
  config:
    import: optional:configserver:http://config-service:8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    # Добавьте эти настройки для повторных попыток
    initial-instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 10
    instance-info-replication-interval-seconds: 30
  instance:
    hostname: user-service
    preferIpAddress: false
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# Настройки для повторных попыток подключения к Eureka
management:
  health:
    eureka:
      enabled: true
