spring:
  datasource:
    url: jdbc:mysql://mysql:3306/user_db
    username: user
    password: password
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: user-service
    preferIpAddress: false
