spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/user_db
    username: user
    password: password
  kafka:
    bootstrap-servers: kafka:29092
  flyway:
    enabled: true
    url: jdbc:postgresql://postgres:5432/user_db
    user: user
    password: password
    schemas: public
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:/db/migration
    clean-disabled: true
    out-of-order: false
  config:
    import: optional:configserver:http://config-service:8888
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: user-service
    preferIpAddress: false
