spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/auth_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: auth-service
    preferIpAddress: false
