spring:
  config:
    import: optional:configserver:http://config-service:8888
  datasource:
    url: jdbc:postgresql://postgres:5432/auth_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: kafka:29092

  flyway:
    enabled: true
    url: jdbc:postgresql://postgres:5432/auth_db
    user: user
    password: password
    schemas: public
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:/db/migration
    clean-disabled: true
    out-of-order: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: auth-service
    preferIpAddress: false
