package org.example.notificationservice.model;

public enum NotificationType {
    TASK_CREATED,
    TASK_UPDATED, 
    TASK_SUBSCRIBED, 
    TASK_UNSUBSCRIBED, 
    TASK_COMPLETED, 
    TASK_DELETED, 
    TASK_STATUS_UPDATED, 
    TASK_ASSIGNEE_UPDATED, 
    COMMENT_CREATED, 
    COMMENT_UPDATED, 
    COMMENT_DELETED, 
    ATTACHMENT_ADDED, 
    ATTACHMENT_DELETED,
    USER_CREATED,
    USER_REGISTRATION,
    USER_PROFILE_UPDATED,
    USER_DELETED,
    USER_ROLE_UPDATE,
    USER_LOGIN,
    LOGIN_FAIL
}
