openapi: 3.0.0
info:
  title: Miro-like Collaborative Whiteboard API
  description: API for a collaborative whiteboard application similar to Miro
  version: 1.0.0

servers:
  - url: http://localhost:8080/api
    description: Development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /auth/signIn:
    post:
      $ref: "./endpoints/auth.yaml#/signIn"

  /auth/signUp:
    post:
      $ref: "./endpoints/auth.yaml#/signUp"

  /auth/assign-role:
    put:
      $ref: "./endpoints/auth.yaml#/assignRole"

  /auth/remove-role:
    put:
      $ref: "./endpoints/auth.yaml#/removeRole"

  /auth/validate:
    get:
      $ref: "./endpoints/auth.yaml#/validateToken"
      
  /auth/refresh:
    post:  
      $ref: './endpoints/auth.yaml#/refresh'

  /users:
    get:
      $ref: "./endpoints/user.yaml#/getAllUsers"  
    post:
      $ref: "./endpoints/user.yaml#/createUser"

  /users/{id}:
    get:
      $ref: "./endpoints/user.yaml#/getUserById"
    put:
      $ref: "./endpoints/user.yaml#/updateUser"
    delete:
      $ref: "./endpoints/user.yaml#/deleteUser"

  /users/all:
    get:
      $ref: "./endpoints/user.yaml#/getAllUsersList"

  /me/profile:
    get:
      $ref: "./endpoints/me.yaml#/getMyProfile"
    put:
      $ref: "./endpoints/me.yaml#/updateMyProfile"
    delete:
      $ref: "./endpoints/me.yaml#/deleteMyProfile"


  /me/tasks:
    get:
      $ref: "./endpoints/meTasks.yaml#/getMyTasks"

  /me/tasks/{id}/subscribe:
    patch:
      $ref: "./endpoints/meTasks.yaml#/subscribeToMeTask"

  /me/tasks/{id}/unsubscribe:
    patch:
      $ref: "./endpoints/meTasks.yaml#/unsubscribeFromMeTask"

  /me/tasks/{id}/complete:
    patch:
      $ref: "./endpoints/meTasks.yaml#/completeMeTask"

  /me/tasks/history:
    get:
      $ref: "./endpoints/meTasks.yaml#/getMyTaskHistory"

  /me/tasks/available-tasks:
    get:
      $ref: "./endpoints/meTasks.yaml#/getAvailableTasksForMe"

  /comments/task/{taskId}:
    post:
      $ref: "./endpoints/comments.yaml#/addComment"
    get:
      $ref: "./endpoints/comments.yaml#/getComments"

  /comments/task/{taskId}/{commentId}:
    put:
      $ref: "./endpoints/comments.yaml#/updateComment"
    delete:
      $ref: "./endpoints/comments.yaml#/deleteComment"

  /tasks:
    get:
      $ref: "./endpoints/tasks.yaml#/getTasks"
    post:
      $ref: "./endpoints/tasks.yaml#/createTask"

  /tasks/all:
    get:
      $ref: "./endpoints/tasks.yaml#/getAllTasks"

  /tasks/bulk:
    post:
      $ref: "./endpoints/tasks.yaml#/createBulkTasks"

  /tasks/due-soon:
    get:
      $ref: "./endpoints/tasks.yaml#/getDueSoonTasks"

  /tasks/{id}:
    get:
      $ref: "./endpoints/tasks.yaml#/getTaskById"
    put:
      $ref: "./endpoints/tasks.yaml#/updateTask"
    delete:
      $ref: "./endpoints/tasks.yaml#/deleteTask"

  /tasks/{id}/status:
    patch:
      $ref: "./endpoints/tasks.yaml#/updateTaskStatus"

  /tasks/{id}/assignees:
    patch:
      $ref: "./endpoints/tasks.yaml#/updateAssignees"

  /tasks/{id}/history:
    get:
      $ref: "./endpoints/tasks.yaml#/getTaskHistory"

  /tasks/assignee/{userId}:
    get:
      $ref: "./endpoints/tasks.yaml#/getTasksByAssignee"

  /attachments/task/{taskId}/batch:
    post:
      $ref: "./endpoints/attachments.yaml#/addAttachments"

  /attachments/task/{taskId}:
    get:
      $ref: "./endpoints/attachments.yaml#/getAttachments"

  /attachments/task/{taskId}/{attachmentIds}:
    delete:
      $ref: "./endpoints/attachments.yaml#/deleteAttachment"

 
